### ISSUE TITLE
Spec file has incorrect season numbers in the Expect statement

### ISSUE THREAD

**Issue by kvignali** [learn-co-curriculum/the-bachelor-todo#1]
User: Vincent Alfieri

Batch: web-0615

Current Lesson: Bringing it all Together - OO Animal Sorter

Location: https://learn.co/tracks/web-development-ruby/ruby/beginning-object-orientation/bringing-it-all-together-oo-animal-sorter?track_id=3273&batch_id=64

Bug Description: Inside of the bachelor spec file you have incorrect season numbers in the Expect statement. They all say "season 10" when the second should be 16 and third be 15.

**Comment by SophieDeBenedetto** [comment]
fixed with latest commit
