### ISSUE TITLE
How do we use JSON?

### ISSUE THREAD

**Issue by m00se333** [learn-co-curriculum/the-bachelor-todo#10]
I ended up just copying and pasting the 2000+ lines of the .json file into my bachelor.rb file and I think that Learn should take the opportunity here to teach students how to use the data from a .json file from elsewhere directly into their programs. I did some googling as to how to do this on my own and my searching came up with nothing useful hence the copy and paste.

I do not understand why the curriculum takes the time to explain what a JSON is and how it's just like a nested data structure without going the extra step to teach us how to use it properly. 

Lacking this knowledge I feel like I missed out on something really useful in this lab.

**Comment by drakeltheryuujin** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
