### ISSUE TITLE
get_average_age_for_seasons mistake

### ISSUE THREAD

**Issue by garettarrowood** [learn-co-curriculum/the-bachelor-todo#3]
All of the tests display "return 26 when...", but they are not all 26 averages.  Most importantly, the first test is inaccurate.  It reads:
expect(get_average_age_for_season(data, "season 10")).to eq(26)
but, it should be:
expect(get_average_age_for_season(data, "season 10")).to eq(25)

**Comment by SophieDeBenedetto** [comment]
Hi @garettarrowood, 

The tests are correct. You are meant to round the average age to the nearest number. Also, not all of the tests display `return 26...`

Test output for this test it: 

``` ruby
 returns 26 when passed the data and the string 'season 10'
 returns 27 when passed the data and the string 'season 11'
 returns 26 when passed the data and the string 'season 12'
```
